name: telegram-file-bot
services:
  - name: file-downloader-bot
    type: web
    instance_type: nano
    ports:
      - port: 8000
        protocol: http
    env:
      - key: PYTHONUNBUFFERED
        value: "1"
    build:
      type: docker
      dockerfile: Dockerfile
    health_check:
      http:
        path: /
        port: 8000
      initial_delay_seconds: 10
      timeout_seconds: 5